# HTTP Listener Configuration
http.host=0.0.0.0
http.port=8081

# Switchee API Configuration
switchee.api.host=api.demo.switchee.co
switchee.api.port=443
switchee.api.protocol=HTTPS
switchee.api.username=your-api-username
switchee.api.password=your-api-password
switchee.api.base.path=/v3.0

# Switchee Auth API Configuration
switchee.auth.api.host=api-auth.demo.switchee.co
switchee.auth.api.port=443
switchee.auth.api.protocol=HTTPS
switchee.auth.api.token.path=/oauth2/token

# Switchee Insights API Configuration
switchee.insights.api.host=api.demo.switchee.co
switchee.insights.api.port=443
switchee.insights.api.protocol=HTTPS
switchee.insights.api.key=XM07YrqlaK9ebIZyRl2rf5nwChdlWTRr3UBkKCym
switchee.insights.api.version=v3.0

# Switchee Authentication
switchee.oauth.client.credentials=Basic NnJkOWttaHBtNTJ2cHFmMDlidDNhY3AzcXM6MTVmZzBxbGt0ZzN0ZXJrNmkyaHAxZGdrcGVodTBxbmJmZWhkdnBrODk5bnZ1N2o3OW44MA==
switchee.oauth.grant.type=client_credentials
switchee.oauth.scope=https://api.demo.switchee.co/api.client

# Salesforce Configuration
salesforce.url=https://login.salesforce.com/services/Soap/u/60.0
salesforce.username=sfs@sfs-566.demo
salesforce.password=Salesforce1

# Salesforce Data Cloud Configuration
salesforce.data.cloud.consumer.key=3MVG98Gq2O8Po4Zn0eG1sxld0Ht.hMevcZ_Dc7BP8Fe_QkaSXBnd_7oNxQdFuWWLadOKqvI.ymMMRR5NLI14h
salesforce.data.cloud.keystore.path=/Users/spajon/AnypointStudio/studio-workspace/switcheesalesforcesync/src/main/resources/keystore.jks
salesforce.data.cloud.store.password=salesforce1
salesforce.data.cloud.key.alias=mulesoftd360
salesforce.data.cloud.subject=sfs@sfs-566.demo
salesforce.data.cloud.audience.url=https://login.salesforce.com
salesforce.data.cloud.source.name=Switchee_property_insight
salesforce.data.cloud.object.name=Switchee_Property_Insight

# Business Configuration
property.id=790247e4-61d1-4fe4-aa6c-8aa0bc4e0531
asset.id=02i7R00001CRxEZQA1

# Scheduling Configuration
scheduler.single.property.frequency=1
scheduler.single.property.time.unit=DAYS
scheduler.d360.sync.frequency=1
scheduler.d360.sync.time.unit=MINUTES

# Content Types
content.type.form.urlencoded=application/x-www-form-urlencoded
content.type.json=application/json
