# HTTP Listener Configuration
http.host=0.0.0.0
http.port=8081

# Switchee API Configuration
switchee.api.host=api.demo.switchee.co
switchee.api.port=443
switchee.api.protocol=HTTPS
switchee.api.username=your-api-username
switchee.api.password=your-api-password
switchee.api.base.path=/v3.0